# Generated by Django 3.1.1 on 2020-09-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property_types', models.ManyToManyField(blank=True, related_name='property_types', to='main.PropertyType')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('available_from', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=400, null=True)),
                ('area', models.CharField(blank=True, max_length=400, null=True)),
                ('adress', models.CharField(max_length=400)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('property_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propertytype')),
            ],
        ),
    ]
