# Generated by Django 3.1.1 on 2020-10-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201004_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretype',
            name='ptype',
        ),
        migrations.AddField(
            model_name='featuretype',
            name='ptype',
            field=models.ManyToManyField(related_name='feature_type', to='main.PropertyType'),
        ),
        migrations.RemoveField(
            model_name='utilities',
            name='ptype',
        ),
        migrations.AddField(
            model_name='utilities',
            name='ptype',
            field=models.ManyToManyField(related_name='utilities', to='main.PropertyType'),
        ),
    ]
