# Generated by Django 3.1.1 on 2020-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201004_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ad_for',
            field=models.CharField(blank=True, choices=[('re', 'Rent'), ('sa', 'Sale'), ('rb', 'Rent for Boys'), ('rs', 'Rent for Girls')], max_length=2, null=True),
        ),
    ]
