# Generated by Django 3.1.1 on 2020-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201004_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='empty_set',
            new_name='set_available',
        ),
        migrations.AlterField(
            model_name='property',
            name='ad_for',
            field=models.CharField(blank=True, choices=[('re', 'Rent'), ('sa', 'Sale'), ('rb', 'Loking for Boy roommate'), ('rs', 'Loking for Girl roommate')], max_length=2, null=True),
        ),
    ]
