# Generated by Django 3.1.1 on 2020-10-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201004_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-id', '-created']},
        ),
        migrations.AddField(
            model_name='property',
            name='preference',
            field=models.ManyToManyField(related_name='properties', to='main.Preference'),
        ),
    ]
