# Generated by Django 3.1.1 on 2020-10-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imguploading', '0004_auto_20201001_1735'),
        ('main', '0008_auto_20201005_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ManyToManyField(related_name='properties', to='imguploading.Images'),
        ),
        migrations.AddField(
            model_name='property',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
