# Generated by Django 3.1.1 on 2020-11-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201113_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
