# Generated by Django 3.1.1 on 2020-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201113_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='drawing_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='hostal_type',
            field=models.CharField(blank=True, choices=[('girl hostal', 'Girl Hostal'), ('boy hostal', 'Boy Hostal')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='people_per_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='publish',
            field=models.BooleanField(choices=[(True, 'Publish'), (False, 'Arcive')], default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='roommate_type',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ad_for',
            field=models.CharField(blank=True, choices=[('re', 'Rent'), ('sa', 'Sale'), ('rb', 'Loking for Boy roommate'), ('rs', 'Loking for Girl roommate')], max_length=2, null=True, verbose_name='Property AD type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.FloatField(blank=True, null=True, verbose_name='property size in sqft'),
        ),
    ]
