# Generated by Django 3.1.1 on 2020-11-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201114_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ad_for',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('sale', 'Sale')], max_length=4, null=True, verbose_name='Property AD type'),
        ),
    ]
