# Generated by Django 3.1.1 on 2020-11-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201122_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latlong',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='thana',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Thana'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='District'),
        ),
    ]
