# Generated by Django 3.1.1 on 2020-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201214_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='feature_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='property_features', to='main.FeatureType'),
        ),
        migrations.AlterField(
            model_name='property',
            name='utility_bill',
            field=models.ManyToManyField(blank=True, null=True, related_name='utility_bill', to='main.Utilities'),
        ),
    ]
