# Generated by Django 3.1.1 on 2021-01-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201214_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='adress',
            new_name='address',
        ),
    ]
