# Generated by Django 3.1.1 on 2021-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210126_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='latlong',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='property',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
