# Generated by Django 3.1.1 on 2021-09-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210926_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='varified',
            field=models.BooleanField(default=False),
        ),
    ]
