# Generated by Django 3.1.1 on 2021-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210929_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='preference',
            field=models.ManyToManyField(blank=True, null=True, related_name='properties', to='main.Preference'),
        ),
    ]
