# Generated by Django 3.1.1 on 2020-09-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imguploading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='timg',
            field=models.ImageField(default='defualt.jpg', upload_to='timg/'),
            preserve_default=False,
        ),
    ]
