# Generated by Django 3.1.1 on 2020-10-06 05:43

from django.db import migrations, models
import imguploading.models


class Migration(migrations.Migration):

    dependencies = [
        ('imguploading', '0004_auto_20201001_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='baseimage',
            field=models.ImageField(blank=True, null=True, upload_to=imguploading.models.getB_path),
        ),
        migrations.AlterField(
            model_name='images',
            name='timage',
            field=models.ImageField(blank=True, null=True, upload_to=imguploading.models.getT_path),
        ),
    ]
