# Generated by Django 3.1.1 on 2020-11-12 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('bn_name', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=360)),
                ('area', models.CharField(blank=True, max_length=360)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('ps', models.CharField(blank=True, max_length=499, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('bn_name', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lon', models.CharField(blank=True, max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='user.citys')),
            ],
        ),
    ]
