# Generated by Django 3.1.1 on 2021-02-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_messages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
