# Generated by Django 3.1.1 on 2020-11-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thnana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('bn_name', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.CharField(blank=True, max_length=50)),
                ('lon', models.CharField(blank=True, max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thana', to='user.citys')),
                ('districts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thana', to='user.districts')),
            ],
        ),
    ]
