# Generated by Django 3.1.1 on 2020-11-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_thnana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thnana',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thana', to='user.citys'),
        ),
    ]
