# Generated by Django 3.1.1 on 2020-11-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201122_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thnana',
            new_name='Thana',
        ),
    ]
